display_name: 纯粹直播
msix_version: 1.2.0.10
publisher: "O=puretech.com, S=Some-State, C=CN"
identity_name: com.mystyle.purelive
logo_path: assets/icons/icon.png
capabilities: internetClient
languages: zh-cn
install_certificate: "false"
certificate_path: ${MSIX_CERT_PATH}
certificate_password: xxxx
signtool_options: /td SHA256