name: pure_live
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+10

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  #hashlib
  hashlib: ^2.0.0
  # network
  flutter_js: ^0.8.2
  flutter_svg: ^2.2.1
  html: ^0.15.4
  http: ^1.1.0
  url_launcher: ^6.1.12
  web_socket_channel: ^3.0.1
  cached_network_image: ^3.3.0
  animated_splash_plus: ^1.0.3
  # ui related
  dynamic_color: ^1.8.1
  waterfall_flow: ^3.1.1
  #Widget
  easy_refresh: ^3.4.0
  flutter_smart_dialog: ^4.9.5 #各种弹窗 Toast/Dialog/Popup
  # barrage wall
  quiver: ^3.2.1
  flex_color_picker: ^3.7.1
  flutter_exit_app: ^1.1.2
  visibility_detector: ^0.4.0+2
  floating: ^6.0.0
  # database
  supabase_flutter: ^2.10.0
  email_validator: ^3.0.0
  font_awesome_flutter: ^10.6.0
  # video player mobile
  media_kit: ^1.2.0                       # Primary package.
  media_kit_video: ^1.3.0                       # For video rendering.
  media_kit_libs_video: ^1.0.6                 # Native video dependencies.
  share_handler: ^0.0.19
  uri_to_file: ^1.0.0
  bordered_text: ^2.0.0
  screen_brightness: ^2.1.2
  move_to_desktop: ^0.0.2
  flutter_volume_controller: ^1.2.7
  flutter_color: ^2.1.0
  crypto_simple: ^3.0.0
  window_manager: ^0.5.0
  windows_single_instance: ^1.0.1
  app_links: ^6.1.4
  protobuf: ^4.1.0
  fixnum: ^1.1.0
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  # system hardware utils
  wakelock_plus: ^1.1.3
  battery_plus: ^6.0.1
  stop_watch_timer: ^3.0.2
  # storage
  file_picker: ^10.2.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.2.2
  flutter_cache_manager: ^3.4.1
  # utils
  get: ^5.0.0-release-candidate-9.3.2
  intl: ^0.20.2
  timezone: ^0.10.0
  date_format: ^2.0.7
  path: ^1.8.5
  file: ^7.0.0
  path_provider: ^2.1.1
  logger: ^2.0.2+1
  crypto: ^3.0.3
  brotli: ^0.6.0
  dlna_dart: ^0.1.0
  dart_tars_protocol:
    git: https://github.com/xiaoyaocz/dart_tars_protocol.git
  tars_dart:
    git:
      url:  https://github.com/xiaoyaocz/dart_simple_live.git
      path: ./simple_live_core/packages/tars_dart
  html_unescape: ^2.0.0
  flutter_inappwebview: ^6.0.0-beta.25
  connectivity_plus: ^6.0.3 
  qr_flutter: ^4.1.0 
  remixicon: ^1.2.0
  mobile_scanner: ^7.0.1 #二维码扫描
  webdav_client: ^1.2.2
  mime: ^2.0.0
  awesome_video_player: ^1.0.5
  device_info_plus: ^11.5.0
  auto_orientation_v2: ^2.3.6
  very_good_infinite_list: ^0.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: any
  json_serializable: ^6.7.1
  build_runner: ^2.3.3
  protoc_builder: ^0.4.1
  flutter_launcher_icons: ^0.14.1
  msix: ^3.16.7
  intl_utils: ^2.8.11
  flutter_lints: ^6.0.0

# flutter pub run flutter_launcher_icons
flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: assets/icons/icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/icon_foreground.png
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: assets/icons/icon.png
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/video/
    - assets/icons/
    - assets/keystore/
    - assets/version.json
    - assets/js/
    - assets/emo/huya/
    - assets/emo/douyu/
    - assets/emo/douyin/
    - assets/emo/bilibili/
    - assets/emo/kuaishou/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf
    - family: PingFang
      fonts:
        - asset: assets/PingFangSC.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# flutter localization settings

flutter_intl:
  enabled: true
  arb_dir: lib/common/l10n
  output_dir: lib/common/l10n/generated

# windows msix package
msix_config:
  display_name: 纯粹直播
  msix_version: 1.0.0.92
  logo_path: assets/icons/icon.png
  certificate_path: assets/keystore/CERTIFICATE.pfx
  certificate_password: xxxx