name: pure_live
description: 纯粹直播,一款开源的第三方多平台直播聚合播放器.

version: 2.0.10+21

environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  #hashlib
  hashlib: ^2.0.0
  # network
  flutter_js: ^0.8.5
  flutter_svg: ^2.2.1
  html: ^0.15.4
  http: ^1.1.0
  url_launcher: ^6.1.12
  web_socket_channel: ^3.0.1
  cached_network_image: ^3.3.0
  animated_splash_plus: ^1.0.3
  # ui related
  dynamic_color: ^1.8.1
  waterfall_flow: ^3.1.1
  #Widget
  easy_refresh: ^3.4.0
  flutter_smart_dialog: ^4.9.5
  # barrage wall
  quiver: ^3.2.1
  flex_color_picker: ^3.7.2
  flutter_exit_app: ^2.0.0
  # database
  supabase_flutter: ^2.10.3
  email_validator: ^3.0.0
  font_awesome_flutter: ^10.6.0
  # video player 
  media_kit:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video
  share_handler: ^0.0.25
  uri_to_file: ^1.0.0
  bordered_text: ^2.0.0
  screen_brightness: ^2.1.2
  move_to_desktop: ^0.0.2
  flutter_volume_controller: ^1.2.7
  flutter_color: ^2.1.0
  crypto_simple: ^3.0.0
  window_manager: ^0.5.1
  launch_at_startup: ^0.5.1
  tray_manager: ^0.5.2
  flutter_single_instance: ^1.7.0
  package_info_plus: ^8.3.1
  flutter_acrylic: ^1.1.4
  protobuf: ^4.1.0
  fixnum: ^1.1.0
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  # system hardware utils
  wakelock_plus: ^1.3.3
  battery_plus: ^7.0.0
  stop_watch_timer: ^3.2.2
  floating: ^6.0.0
  # storage
  file_picker: ^10.3.6
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  flutter_cache_manager: ^3.4.1
  # utils
  get: ^5.0.0-release-candidate-9.3.2
  intl: ^0.20.2
  timezone: ^0.10.1
  date_format: ^2.0.9
  path: ^1.9.1
  file: ^7.0.1
  path_provider: ^2.1.5
  logger: ^2.6.2
  crypto: ^3.0.7
  brotli: ^0.6.0
  dlna_dart: ^0.1.0
  dart_tars_protocol:
    git: https://github.com/xiaoyaocz/dart_tars_protocol.git
  tars_dart:
    git:
      url: https://github.com/xiaoyaocz/dart_simple_live.git
      path: ./simple_live_core/packages/tars_dart
  html_unescape: ^2.0.0
  flutter_inappwebview: ^6.2.0-beta.2
  qr_flutter: ^4.1.0
  remixicon: ^1.2.0
  mobile_scanner: ^7.1.3 #二维码扫描
  webdav_client: ^1.2.2
  mime: ^2.0.0
  flv_lzc:
    git: https://github.com/liuchuancong/flv_lzc.git
  device_info_plus: ^12.2.0
  auto_orientation_v2: ^2.3.6
  dart_quickjs:
    git: https://github.com/xiaoyaocz/dart_quickjs.git
  open_filex: ^4.7.0
  rxdart: ^0.28.0
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  markdown_widget: ^2.3.2+8
  google_fonts: ^6.3.3
  back_button_interceptor: ^8.0.4
  screen_retriever:
     git:
      url: https://github.com/MSOB7YY/screen_retriever.git
      path: ./packages/screen_retriever
      ref: main
dependency_overrides:
  media_kit:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video
  media_kit_libs_linux:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/linux/media_kit_libs_linux
  media_kit_libs_ios_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/ios/media_kit_libs_ios_video
  media_kit_libs_android_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/android/media_kit_libs_android_video
  media_kit_libs_windows_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/windows/media_kit_libs_windows_video
  media_kit_libs_macos_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/macos/media_kit_libs_macos_video
  screen_retriever:
     git:
      url: https://github.com/MSOB7YY/screen_retriever.git
      path: ./packages/screen_retriever
      ref: main
dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: any
  json_serializable: ^6.7.1
  build_runner: ^2.3.3
  protoc_builder: ^0.4.1
  flutter_launcher_icons: ^0.14.4
  msix: ^3.16.12
  intl_utils: ^2.8.11
  flutter_lints: ^6.0.0
  dmg: ^0.1.7
# flutter pub run flutter_launcher_icons
flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: assets/icons/icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/icon_foreground.png
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: assets/icons/icon.png
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: assets/icons/icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/video/
    - assets/icons/
    - assets/keystore/
    - assets/version.json
    - assets/emo/huya/
    - assets/emo/douyu/
    - assets/emo/douyin/
    - assets/emo/bilibili/
    - assets/emo/kuaishou/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf
    - family: PingFang
      fonts:
        - asset: assets/PingFangSC.ttf


flutter_intl:
  enabled: true
  arb_dir: lib/common/l10n
  output_dir: lib/common/l10n/generated

