
app_id: C76CD88E-EB3F-49AD-9191-65691050035A
publisher: My Company, Inc.
publisher_url: https://github.com/liuchuancong/pure_live
display_name: 纯粹直播
create_desktop_icon: true
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en
  - zh