name: app-build-action

# æ¨é€Tagæ—¶è§¦å‘ æˆ–è€… æ‰‹åŠ¨è§¦å‘
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'
  push:
    tags:
      - "v*"
  schedule:
    - cron: '0 10 * * *'

jobs:
  build-android:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      # ç­¾å‡ºä»£ç 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}

      # APKç­¾åè®¾ç½®
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: key.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      # è®¾ç½®JAVAç¯å¢ƒ
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: 'gradle'

      # è®¾ç½®Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.x'
          cache: true 

      # æ›´æ–°Flutterçš„packages
      - name: Restore packages
        run: flutter pub get

      # æ‰“åŒ…APK
      - name: Build APK
        run: flutter build apk --release --split-per-abi
      
      # ä¸Šä¼ APKè‡³Artifacts
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk

      - name: Get latest release version
        id: latest_release
        shell: pwsh
        run: |
          $LatestRelease = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases/latest"
          echo "::set-output name=latest_tag::$($LatestRelease.tag_name)"

      # ä½¿ç”¨è·å–åˆ°çš„æœ€æ–°æ ‡ç­¾åï¼ˆå¯é€‰ï¼‰
      - name: Use the latest tag
        run: echo "The latest release tag is ${{ steps.latest_release.outputs.latest_tag }}"

      # è¯»å–ç‰ˆæœ¬ä¿¡æ¯
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:name: app-build-action

# æ¨é€Tagæ—¶è§¦å‘ æˆ–è€… æ‰‹åŠ¨è§¦å‘
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'
  push:
    tags:
      - "v*"
  schedule:
    - cron: '0 10 * * *'

jobs:
  build-android:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      # ç­¾å‡ºä»£ç 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}

      # APKç­¾åè®¾ç½®
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: key.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      # è®¾ç½®JAVAç¯å¢ƒ
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: 'gradle'

      # è®¾ç½®Flutter
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.x'
          cache: true 

      # æ›´æ–°Flutterçš„packages
      - name: Restore packages
        run: flutter pub get

      # æ‰“åŒ…APK
      - name: Build APK
        run: flutter build apk --release --split-per-abi
      
      # ä¸Šä¼ APKè‡³Artifacts
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: |
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk

      - name: Get latest release version
        id: latest_release
        shell: pwsh
        run: |
          $LatestRelease = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases/latest"
          echo "::set-output name=latest_tag::$($LatestRelease.tag_name)"

      # ä½¿ç”¨è·å–åˆ°çš„æœ€æ–°æ ‡ç­¾åï¼ˆå¯é€‰ï¼‰
      - name: Use the latest tag
        run: echo "The latest release tag is ${{ steps.latest_release.outputs.latest_tag }}"

      # è¯»å–ç‰ˆæœ¬ä¿¡æ¯
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: assets/version.json
      - name: Echo version
        run: echo "${{ fromJson(steps.version.outputs.content).version }}"
      - name: Echo version content
        run: echo "${{ fromJson(steps.version.outputs.content).version_desc }}"

      # ä¸Šä¼ è‡³Release
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ github.event.inputs.tag_name }}"
          body: "${{ fromJson(steps.version.outputs.content).version_desc }}"
          prerelease: false
          token: ${{ secrets.TOKEN }}
          files: |
            build/app/outputs/flutter-apk/app-x86_64-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      # å®Œæˆ
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  # æ‰“åŒ…Windows
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # ç­¾å‡ºä»£ç 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}

      # è®¾ç½®Flutterç¯å¢ƒ
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.x"
          cache: true
      - name: Enable Flutter Desktop
        run: flutter config --enable-windows-desktop
      - name: Restore Packages
        run: flutter pub get

      # è®¾ç½®flutter_distributorç¯å¢ƒ
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      # build Windows ZIP\MSIX
      - name: Build Windows
        run: flutter_distributor package --platform windows --targets msix,zip,exe --skip-clean

      # ä¸Šä¼ Windowsè‡³Artifacts
      - name: Upload Windows APP to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            build/dist/*/*.msix
            build/dist/*/*.zip
            build/dist/*/*.exe

      # è·å–æœ€æ–°Releaseç‰ˆæœ¬ï¼ˆå¯é€‰ï¼‰
      - name: Get latest release version
        id: latest_release
        shell: pwsh
        run: |
          $LatestRelease = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases/latest"
          echo "::set-output name=latest_tag::$($LatestRelease.tag_name)"

      # ä½¿ç”¨è·å–åˆ°çš„æœ€æ–°æ ‡ç­¾åï¼ˆå¯é€‰ï¼‰
      - name: Use the latest tag
        run: echo "The latest release tag is ${{ steps.latest_release.outputs.latest_tag }}"

      # è¯»å–ç‰ˆæœ¬ä¿¡æ¯
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: assets/version.json
      - name: Echo version
        run: echo "${{ fromJson(steps.version.outputs.content).version }}"
      - name: Echo version content
        run: echo "${{ fromJson(steps.version.outputs.content).version_desc }}"

      # ä¸Šä¼ è‡³Release
      - name: Upload Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          name: "${{ github.event.inputs.tag_name }}"
          body: "${{ fromJson(steps.version.outputs.content).version_desc }}"
          prerelease: false
          token: ${{ secrets.TOKEN }}
          files: |
            build/dist/*/*.msix
            build/dist/*/*.zip
            build/dist/*/*.exe

      # å®Œæˆ
      - run: echo "ğŸ Windows job's status is ${{ job.status }}."

          path: assets/version.json
      - name: Echo version
        run: echo "${{ fromJson(steps.version.outputs.content).version }}"
      - name: Echo version content
        run: echo "${{ fromJson(steps.version.outputs.content).version_desc }}"

      # ä¸Šä¼ è‡³Release
      - name: Upload Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          name: "${{ github.event.inputs.tag_name }}"
          body: "${{ fromJson(steps.version.outputs.content).version_desc }}"
          prerelease: false
          token: ${{ secrets.TOKEN }}
          files: |
            build/app/outputs/flutter-apk/app-x86_64-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      # å®Œæˆ
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  # æ‰“åŒ…Windows
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # ç­¾å‡ºä»£ç 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name }}

      # è®¾ç½®Flutterç¯å¢ƒ
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.x"
          cache: true
      - name: Enable Flutter Desktop
        run: flutter config --enable-windows-desktop
      - name: Restore Packages
        run: flutter pub get

      # è®¾ç½®flutter_distributorç¯å¢ƒ
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      # build Windows ZIP\MSIX
      - name: Build Windows
        run: flutter_distributor package --platform windows --targets msix,zip,exe --skip-clean

      # ä¸Šä¼ Windowsè‡³Artifacts
      - name: Upload Windows APP to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            build/dist/*/*.msix
            build/dist/*/*.zip
            build/dist/*/*.exe

      # è·å–æœ€æ–°Releaseç‰ˆæœ¬ï¼ˆå¯é€‰ï¼‰
      - name: Get latest release version
        id: latest_release
        shell: pwsh
        run: |
          $LatestRelease = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases/latest"
          echo "::set-output name=latest_tag::$($LatestRelease.tag_name)"

      # ä½¿ç”¨è·å–åˆ°çš„æœ€æ–°æ ‡ç­¾åï¼ˆå¯é€‰ï¼‰
      - name: Use the latest tag
        run: echo "The latest release tag is ${{ steps.latest_release.outputs.latest_tag }}"

      # è¯»å–ç‰ˆæœ¬ä¿¡æ¯
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: assets/version.json
      - name: Echo version
        run: echo "${{ fromJson(steps.version.outputs.content).version }}"
      - name: Echo version content
        run: echo "${{ fromJson(steps.version.outputs.content).version_desc }}"

      # ä¸Šä¼ è‡³Release
      - name: Upload Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          name: "${{ github.event.inputs.tag_name }}"
          body: "${{ fromJson(steps.version.outputs.content).version_desc }}"
          prerelease: false
          token: ${{ secrets.TOKEN }}
          files: |
            build/dist/*/*.msix
            build/dist/*/*.zip
            build/dist/*/*.exe

      # å®Œæˆ
      - run: echo "ğŸ Windows job's status is ${{ job.status }}."
